project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "SEEA AFE"
  navbar:
    pinned: true
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: "Documentation"
        href: documentation/index.qmd
      - text: "Dashboard"
        href: dashboard/index.qmd
      - about.qmd
  sidebar:
    - title: Documentation
      contents:
        - section: "Documentation"
          href: documentation/index.qmd
          contents:
              - text: "Diagnostic Review"
                href: documentation/01_diagnostic_review.qmd
              - text: "Analytical Results"
                href: documentation/02_analytical_results.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



