project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "SEEA AFE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: documentation
        text: Documentation
      - about.qmd
  sidebar:
    contents: auto

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



